package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

var envVarRegex = regexp.MustCompile(`\{env:([A-Za-z_][A-Za-z0-9_]*)\}`)

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Initialize opencode-kit setup",
		Long: `Setup wizard that:
  1. Checks opencode config directory exists
  2. Checks opencode.json / opencode.jsonc exists and parses it
  3. Creates opencode.env from opencode.env.example if needed
  4. Seeds the model registry
  5. Runs auto-healing
  6. Prints summary + next steps`,
		RunE: func(cmd *cobra.Command, args []string) error {
			configDir := OpenCodeConfigDir()

			fmt.Println("=== opencode-kit Init ===")
			fmt.Println()

			fmt.Println("[1/6] Config directory...")
			_, err := os.Stat(configDir)
			if os.IsNotExist(err) {
				fmt.Printf("  Creating %s...\n", configDir)
				if err := os.MkdirAll(configDir, 0755); err != nil {
					return fmt.Errorf("create config dir: %w", err)
				}
			} else if err != nil {
				return fmt.Errorf("stat config dir: %w", err)
			} else {
				fmt.Printf("  OK: %s\n", configDir)
			}
			fmt.Println()

			fmt.Println("[2/6] Config file...")
			configPath := OpenCodeConfigPath()
			if _, err := os.Stat(configPath); os.IsNotExist(err) {
				fmt.Printf("  WARN: %s not found\n", opencodeConfigName())
				fmt.Println("  Run 'okit generate config' to create it")
			} else {
				data, err := os.ReadFile(configPath)
				if err != nil {
					fmt.Printf("  WARN: cannot read: %v\n", err)
				} else {
					fmt.Printf("  OK: %s (%d bytes)\n", configPath, len(data))
				}
			}
			fmt.Println()

			fmt.Println("[3/6] Environment file...")
			envPath := filepath.Join(configDir, "opencode.env")
			if _, err := os.Stat(envPath); os.IsNotExist(err) {
				vars := scanEnvVarsFromConfig(configPath)
				if len(vars) > 0 {
					content := "# Auto-generated by okit init\n"
					content += "# API keys referenced in opencode.json\n"
					content += "# Uncomment and set values not already in your shell environment.\n\n"
					existing := make(map[string]bool)
					for _, line := range os.Environ() {
						parts := strings.SplitN(line, "=", 2)
						if len(parts) == 2 {
							existing[parts[0]] = parts[1] != ""
						}
					}
					for _, v := range vars {
						if existing[v] {
							content += fmt.Sprintf("%s=\n", v)
						} else {
							content += fmt.Sprintf("# %s=\n", v)
						}
					}
					if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
						fmt.Printf("  WARN: cannot create opencode.env: %v\n", err)
					} else {
						fmt.Printf("  Created: %s (%d env vars detected from config)\n", envPath, len(vars))
					}
				} else {
					fmt.Println("  WARN: no {env:...} references found in config, opencode.env not created")
				}
			} else {
				fmt.Printf("  OK: %s\n", envPath)
			}
			fmt.Println()

			fmt.Println("[4/6] Seeding model registry...")
			d, err := openDB(nil)
			if err != nil {
				fmt.Printf("  WARN: open db: %v\n", err)
			} else {
				fmt.Printf("  OK: database at %s\n", d.DBPath())
				d.Close()
			}
			fmt.Println()

			fmt.Println("[5/6] Running auto-heal...")
			d, err = openDB(nil)
			if err != nil {
				fmt.Printf("  WARN: open db: %v\n", err)
			} else {
				report, err := runHeal(d)
				if err != nil {
					fmt.Printf("  WARN: heal: %v\n", err)
				} else if report.IssuesFound > 0 {
					fmt.Printf("  Healed: %d issues found, %d fixed\n", report.IssuesFound, report.IssuesFixed)
				} else {
					fmt.Println("  OK: no issues found")
				}
				d.Close()
			}
			fmt.Println()

			fmt.Println("[6/6] Summary")
			fmt.Printf("  Configuration: %s\n", configDir)
			fmt.Printf("  Config file:   %s %s\n", opencodeConfigName(), checkFileExists(configPath))
			fmt.Printf("  Env file:      opencode.env %s\n", checkFileExists(envPath))
			fmt.Println()
			fmt.Println("Next steps:")
			fmt.Println("  1. Edit opencode.env with your API keys")
			fmt.Println("  2. Run 'okit daily' to discover and audit models")
			fmt.Println("  3. Run 'okit doctor' to verify everything works")
			fmt.Println()
			fmt.Printf("Tip: run 'source opencode.env' from %s to load API keys\n", configDir)

			return nil
		},
	}
}

func scanEnvVarsFromConfig(configPath string) []string {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil
	}
	matched := envVarRegex.FindAllSubmatch(data, -1)
	seen := make(map[string]bool)
	var vars []string
	for _, m := range matched {
		name := string(m[1])
		if !seen[name] {
			seen[name] = true
			vars = append(vars, name)
		}
	}
	sort.Strings(vars)
	return vars
}

func checkFileExists(path string) string {
	info, err := os.Stat(path)
	if os.IsNotExist(err) {
		return "(not found)"
	}
	if err != nil {
		return fmt.Sprintf("(error: %v)", err)
	}
	return fmt.Sprintf("(%d bytes)", info.Size())
}
