ALTER TABLE providers ADD COLUMN timeout_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE providers ADD COLUMN header_timeout_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE providers ADD COLUMN chunk_timeout_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE providers ADD COLUMN enterprise_url TEXT NOT NULL DEFAULT '';
ALTER TABLE providers ADD COLUMN set_cache_key INTEGER NOT NULL DEFAULT 0;
ALTER TABLE providers ADD COLUMN api_package TEXT NOT NULL DEFAULT '';
ALTER TABLE providers ADD COLUMN env_list TEXT NOT NULL DEFAULT '';

ALTER TABLE models ADD COLUMN interleaved TEXT NOT NULL DEFAULT '';
ALTER TABLE models ADD COLUMN fine_tuning INTEGER NOT NULL DEFAULT 0;
ALTER TABLE models ADD COLUMN classification INTEGER NOT NULL DEFAULT 0;
ALTER TABLE models ADD COLUMN moderation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE models ADD COLUMN created_timestamp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE models ADD COLUMN owned_by TEXT NOT NULL DEFAULT '';
