ALTER TABLE skills ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE skills ADD COLUMN category TEXT NOT NULL DEFAULT '';
ALTER TABLE skills ADD COLUMN tags TEXT NOT NULL DEFAULT '';
ALTER TABLE skills ADD COLUMN triggers TEXT NOT NULL DEFAULT '';
ALTER TABLE skills ADD COLUMN size_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE skills ADD COLUMN filename TEXT NOT NULL DEFAULT '';
